-- AlterTable
ALTER TABLE "Job" ALTER COLUMN "city" SET DEFAULT '',
ALTER COLUMN "country" SET DEFAULT '',
ALTER COLUMN "jobType" SET DEFAULT 'FULL_TIME',
ALTER COLUMN "state" SET DEFAULT '',
ALTER COLUMN "workExperience" SET DEFAULT '';
